{"componentChunkName":"component---src-pages-answer-mdx-frontmatter-id-tsx-content-file-path-contents-js-async-error-handling-mdx","path":"/answer/klc1zg6ljoul/","result":{"data":{"mdx":{"id":"ffa48541-20f2-5616-bc4f-1885b99081c0","frontmatter":{"title":"비동기 에러 핸들링","date":"2023/11/05","tags":["JS","에러 핸들링"],"relatedLinks":["https://ko.javascript.info/try-catch","https://ko.javascript.info/promise-error-handling#tasks"]}}},"pageContext":{"id":"ffa48541-20f2-5616-bc4f-1885b99081c0","frontmatter__id":"klc1zg6ljoul","__params":{"frontmatter__id":"klc1zg6ljoul"},"frontmatter":{"id":"klc1zg6ljoul","title":"비동기 에러 핸들링","date":"2023-11-05T00:00:00.000Z","tags":["JS","에러 핸들링"],"relatedLinks":["https://ko.javascript.info/try-catch","https://ko.javascript.info/promise-error-handling#tasks"],"questionType":"빈칸","question":["<code lang=javascript>new Promise((res, rej) => {\n\tsetTimeout(() => {\n\t\tthrow new Error();\n\t}, 1000);\n}).catch(() => console.log('catch'));</code>","1000ms 후 프로미스 객체의 상태는","<빈칸>","이며, 콘솔에 \"catch\"가","<빈칸>"],"choices":[["Pending","Rejected","Fullfilled","셋 다 아님"],["출력됨","출력되지 않음"]],"answer":["A","B"],"level":3,"category":"js","description":["try...catch는 동기적으로 동작해요.","실행 함수 종료 이후애 에러가 발생해요."]}}},"staticQueryHashes":["1003650488"],"slicesMap":{}}